<!DOCTYPE html>
<html>
<head>
    <title>Anniversary Contribution Report</title>
    <style>
        body {
            font-family: sans-serif;
            margin: 30px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .header img {
            width: 80px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 25px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
        }

        .footer {
            margin-top: 40px;
            font-size: 14px;
            text-align: right;
        }

        .total {
            font-weight: bold;
            background: #f2f2f2;
        }
    </style>
</head>
<body>

<div class="header" style="display: flex; align-items: center; justify-content: space-between; gap: 18px; text-align: left; border-bottom: 2px solid #6a8dff; padding-bottom: 14px; margin-bottom: 20px;">
    <?php if (!empty($logoPath)): ?>
        <img src="<?= $logoPath ?>" alt="NLBF Logo" style="width: 90px; height: 90px; object-fit: contain; border-radius: 14px; flex-shrink: 0; background: #f8fafc; padding: 8px; box-sizing: border-box;">
    <?php endif; ?>
    <div style="flex: 1; min-width: 0;">
        <h3 style="margin: 0 0 6px 0; font-size: 22px;">New Life Believers Fellowship International Incorporated</h3>
        <h4 style="margin: 0; font-size: 16px; color: #6a8dff;">Anniversary Contribution Report</h4>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Family Name</th>
            <th>Description</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <?php $totalAmount = 0; ?>
        <?php foreach ($contribution as $contribution): ?>
            <tr>
                <td><?= esc($contribution['date']) ?></td>
                <td><?= esc($contribution['family_name']) ?></td>
                <td><?= esc($contribution['description']) ?></td>
                <td>P<?= number_format($contribution['amount'], 2) ?></td>
            </tr>
            <?php $totalAmount += $contribution['amount']; ?>
        <?php endforeach; ?>
        <tr class="total">
            <td colspan="3">Total</td>
            <td>P<?= number_format($totalAmount, 2) ?></td>
        </tr>
    </tbody>
</table>

<div class="footer">
    Generated by: <?= session()->get('username') ?? 'Admin' ?><br>
    Printed on: <?= date('F d, Y h:i A') ?>
</div>

</body>
</html>
